=== LyubovTatur/labs_front/lab_11/struct.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css"; href="style.css"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="BookKatalog">
<xs:complexType>
<xs:sequence>
<xs:element name="book" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>

    <xs:element name="name" type="xs:string"/>
<xs:element name="author" type="xs:string"/>
<xs:element name="ISBN_number" type="xs:positiveInteger"/>
<xs:element name="cost" type="xs:positiveInteger"/>
<xs:element name="summary" type="xs:string"/>
<xs:element name="image" maxOccurs="unbounded" type="xs:string"/>
<xs:element name="page_count" type="xs:positiveInteger"/>
<xs:element name="year_of_production" type="xs:string"/>
<xs:element name="place_of_production" maxOccurs="unbounded" type="xs:string"/>
<xs:element name="language" maxOccurs="unbounded" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== LyubovTatur/labs_front/lab_11/elem.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css"; href="style.css"?>
<BookKatalog xsi:noNamespaceSchemaLocation="struct.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
<book>
<name>The village of numbers</name>
<author>Oleg</author>
<ISBN_number>616513</ISBN_number>

<cost>1651</cost>

<summary>No summary</summary>

<image>ihjngksfjddshgkjehfsofsbf</image>

<page_count>646</page_count>

<year_of_production>2021</year_of_production>

<place_of_production>Dgahid2</place_of_production>

<language>English</language>

</book>

</BookKatalog>
