=== LyubovTatur/labs_front/lab_11/timetable/timetable_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>

<!--5. Расписание занятий. Расписание занятий у каждой группы свое. Для-->
<!--каждого дня недели расписание свое. При этом некоторые дни недели могут-->
<!--быть свободны. Кроме этого расписание на четной и нечетной неделе может-->
<!--отличаться. В расписании указывается название предмета, тип (лекция,-->
<!--практика, лабораторные работы), аудитория (корпус и номер), в которой-->
<!--будет проходить занятие, ссылка на информацию о преподавателе, которая-->
<!--хранится в отдельном файле. В информацию о преподавателе входит ФИО,-->
<!--должность, кафедра, университет, контактная информация (телефон рабочий,-->
<!--домашний, E-mail). Необходимо учесть, что рабочий телефон может быть не-->
<!--один, домашнего телефона может не быть или быть несколько, e-mail может-->
<!--не быть или быть несколько.-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="timetable_catalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="timetable">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="group" type="xs:string"/>
                            <xs:element name="week_day">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="week_day_name" type="xs:string"/>
                                        <xs:element name="subjects">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="title" type="xs:string"/>
                                                    <xs:element name="type_of_lesson">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="lecture"/>
                                                                <xs:enumeration value="practice"/>
                                                                <xs:enumeration value="laboratory work"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="classroom_number" type="xs:positiveInteger"/>
                                                    <xs:element name="teacher" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="parity">
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LyubovTatur/labs_front/lab_11/timetable/timetable.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<timetable_catalog xsi:noNamespaceSchemaLocation="timetable_schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="$LOCAL_SCHEMA$">
    <timetable>
        <group>1</group>
        <week_day>
            <week_day_name>понидельник</week_day_name>
            <subjects>
                <title>матеша</title>
                <type_of_lesson>lecture</type_of_lesson>
                <classroom_number>445</classroom_number>
                <teacher>Мистер математик</teacher>
            </subjects>
        </week_day>
        <parity>числитель</parity>
    </timetable>
    <timetable>
        <group>2</group>
        <week_day>
            <week_day_name>понидельник</week_day_name>
            <subjects>
                <title>русский язык</title>
                <type_of_lesson>practice</type_of_lesson>
                <classroom_number>666</classroom_number>
                <teacher>Миссис РУсица</teacher>
            </subjects>
        </week_day>
        <parity>числитель</parity>
    </timetable>
</timetable_catalog>
